arrayLayout: List<{type}>
modelFileName: "{{object_name | snake_case}}.dart"
types:
    String:
        default: String
        format:
            Date: Date
            DateTime: DateTime
            Password: String
            Byte: Byte
            Binary: String
    Number:
        default: double
        format:
            Float: float
            Double: double
    Integer:
        default: Integer
        format:
            Int32: int
            int64: int
    Boolean:
        default: bool
extended:
    feature: FAQ
